### PR TITLE
Update  Employee Profile Data

### PR DESCRIPTION
**Pull request by Damola18**
This PR updates employee profile data. Also fixes the blurry images on the iq social section

image

Screenshot 2024-06-13 at 16 06 38

closes https://github.com/EveripediaNetwork/issues/issues/2758

### CODE REVIEW

**Review by Simplypheyie96 — COMMENTED** [review]
something small, but i am not sure why the border here is broken
image
Everything else looks great

**Comment by Damola18** [comment]
> something small, but i am not sure why the border here is broken
> image
> Everything else looks great

Broken border?, let me check that

**Comment by Damola18** [comment]
> something small, but i am not sure why the border here is broken image Everything else looks great



> something small, but i am not sure why the border here is broken image Everything else looks great

fixed

**Comment by Damola18** [comment]
> Implementation for mobile image
> 
> Design Screenshot 2024-06-13 at 3 17 31 PM
> 
> the vatical padding is 24px while the horizontal padding is 20px

fixed

**Review by Dewalz — APPROVED** [review]

**Review by Simplypheyie96 — APPROVED** [review]

**Pull request merged**
