### PR TITLE
Animation iteration

### PR DESCRIPTION
**Pull request by Aliiiu**
This PR works on improving the animation in the hero section and implementing a fade-in animation style

### CODE REVIEW

**Review by Simplypheyie96 — APPROVED** [review]

**Comment by kesar** [comment]
image

this doesnt look good. it was looking better before

**Comment by Simplypheyie96** [comment]
> image
> 
> this doesnt look good. it was looking better before

I already discussed this with him in on discord about the issue.
image
but he couldn't see it on his end, so i thought maybe it wasn't loading properly for me, which is why i approved it.
image

For the animation, I already discussed with him too. He changed it to a slight fade in for the rest of the landing page but i wanted it to be tested first to see if that was what was expected
image

**Comment by Simplypheyie96** [comment]
I already discussed with @Softdev1 today too, but i think the only thing that would make the hero section work is to create a video in high resolution that will be the same size as the header, but paola said it wasn't possible to make that happen.

reducing the size of the video to center it made the video look weird in the middle of the dark background because the edges of the video was not really dark in the first place., 
image

so i added gradients to make the edges blend into the background, but on implementation, it wasn't really looking great.
image

---
I would suggest we go with a static background with high resolution image.
image

**Comment by kesar** [comment]
we already created a higher quality video for navbar and its already replaced. that was the needed change. The other feedback was to replace the slide up effect for a fade-in one for the text in the site

**Comment by Simplypheyie96** [comment]
> we already created a higher quality video for navbar and its already replaced. that was the needed change. The other feedback was to replace the slide up effect for a fade-in one for the text in the site

I think the task was misleading because i was told to center the video

**Review by Simplypheyie96 — APPROVED** [review]

**Pull request merged**
