### PR TITLE
Gradient animation

### PR DESCRIPTION
**Pull request by Royal-lobster**
# Changes
 - Adds subtle gradient animation to gradient particles at background

# Links
- https://braindao-ui-git-gradient-animation-prediqt.vercel.app/

# Screenshots

https://user-images.githubusercontent.com/52039218/196972018-f11ce543-90ac-4b2b-aa55-f9b6e624db1d.mp4

### CODE REVIEW

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
movements are kinda too slow

- for this part, the gradient should move beneath the glassy frame to accentuate it more  
image
- we should give the gradient more surface area. it is too restricted
image

- this is the only part where the gradient is restricted in movement to keep it with the glassy frame here 
image

**Comment by Royal-lobster** [comment]
@Simplypheyie96 please add review to this PR again

**Comment by Simplypheyie96** [comment]
> @Simplypheyie96 please add review to this PR again

I will try again later. The Braindao preview Page is not loading.

**Comment by Royal-lobster** [comment]
ohh 😮 can i get a screen shot of it ?

**Comment by Simplypheyie96** [comment]
> ohh 😮 can i get a screen shot of it ?

image

**Comment by Royal-lobster** [comment]
@Simplypheyie96  once check this link - https://braindao-ui-git-gradient-animation-prediqt.vercel.app/

**Comment by Simplypheyie96** [comment]
> https://braindao-ui-git-gradient-animation-prediqt.vercel.app/

@srujan so it is not yet there. It has some ripple effects that makes it look weird. it's ball of a blue/pink vivid gradient and I noticed some pauses in the movements of the gradient ball that makes it look like its seizing, so the movement should be continuous but very slow such that it won't be disracting. that's it.

**Comment by Simplypheyie96** [comment]
https://user-images.githubusercontent.com/99387231/197401862-9078cf9a-e86a-4359-978f-ae2c2fba36b1.mp4
I did this animations for the brainies once. you can see the way the pink blur are slowly moving from one end to another. Let's do something similar @Royal-lobster

**Comment by Royal-lobster** [comment]
> https://user-images.githubusercontent.com/99387231/197401862-9078cf9a-e86a-4359-978f-ae2c2fba36b1.mp4 I did this animations for the brainies once. you can see the way the pink blur are slowly moving from one end to another. Let's do something similar @Royal-lobster

Thanks this helps. i will try to replicate similar.

**Pull request closed without merging**
